language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - npm install

script: ./vendor/bin/phpunit --configuration ./travis-ci.xml
